config/routes.rb
Rails.application.routes.draw do

  devise_for :employees
  #devise_for :candidates
  devise_for :companies
  devise_for :users

  resources :employees
  resources :m_countries
  resources :messageemployees
  resources :countries
  resources :aplicationjobs
  resources :categories
  resources :companies
  resources :jobs
  resources :articles

  get 'aplicationjobs/new/:job_id', to: 'aplicationjobs#new'
  get 'messageemployees/new/:candidate_id', to: 'messageemployees#new'

  #devise_for :users
  #match '/auth/:provider/callback', :to => 'sessions#create', via: :get
  get 'home', to: 'home#index'
       root :to => "home#index" #page index by default

  #resources :administration
  get 'administration/jobs', to: 'administration#jobs'  #donde se guardan los trabajos aplicados para un usuario
  get 'administration/companies', to: 'administration#companies'  #donde se guardan las aplicaciones de trabajo para esa compannia
  get 'administration/employees', to: 'administration#employees' #donde se guardan los mensajes de los usuarios empleados

  post 'search', to: 'home#search'

end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true,
            length: { minimum: 5 }
  has_attached_file :image,  default_url: ""
  validates_attachment_content_type :image, :content_type => %w(image/jpeg image/jpg image/png)
  #validates_attachment_presence :image

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |article|
        csv << article.attributes.values_at(*column_names)
      end
    end
  end


  #self.page = 5
  #gema filterrific para paginado y filtrado
  filterrific(
      default_filter_params: { sorted_by: 'created_at_desc' },
      available_filters: [
          :sorted_by,
          :search_query,
          :with_country_id,
          :with_created_at_gte
      ]
  )

  scope :search_query, lambda { |query|
    return nil  if query.blank?
    # condition query, parse into individual keywords
    terms = query.downcase.split(/\s+/)
    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conditions = 1
    where(
        terms.map {
          or_clauses = [
              "LOWER(articles.title) LIKE ?",
          ].join(' OR ')
          "(#{ or_clauses })"
        }.join(' AND '),
        *terms.map { |e| [e] * num_or_conditions }.flatten
    )
  }

  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
      when /^created_at_/
        order("articles.created_at #{ direction }")
      when /^name_/
        order("LOWER(articles.title) #{ direction },")
      else
        raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }
  scope :with_category_id, lambda { |category_ids|
    where(:category_id => [*category_ids])
  }
  scope :with_company_id, lambda { |company_ids|
    where(:company_id => [*company_ids])
  }
  scope :with_created_at_gte, lambda { |ref_date|
    where('jobs.created_at >= ?', ref_date)
  }

  delegate :name, :to => :country, :prefix => true

  def self.options_for_sorted_by
    [
        ['Name (a-z)', 'name_asc'],
        ['Registration date (newest first)', 'created_at_desc'],
        ['Registration date (oldest first)', 'created_at_asc'],
        ['Country (a-z)', 'country_name_asc']
    ]
  end

  def full_name
    [last_name, first_name].compact.join(', ')
  end

  def decorated_created_at
    created_at.to_date.to_s(:long)
  end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :new, only: :create
  #load_and_authorize_resource
  load_and_authorize_resource except: [:create]

  def index
    @title = 'CRUD Articles'
    #@articles = Article.all
    @filterrific = initialize_filterrific(
        Article,
        params[:filterrific]
    ) or return
    @articles = @filterrific.find.page(params[:page]).per(params[:cantd])

    respond_to do |format|
      format.html
      format.js
      format.csv { send_data @articles.to_csv }
      format.xls
    end


  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text,:image)
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end



end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb


<%= form_for @article do |f| %>
    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:</h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field col-lg-6">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>

    <div class="field col-lg-6">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>

    <div class="field col-lg-6">
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </div>

    <p>
      <%= f.submit %>
    </p>
<% end %>


app/views/articles/_list.html.erb
<div id="filterrific_results">
  <div class="acciones_filtros_search">
    <%= page_entries_info articles %>
  </div>

    <% articles.dup.each do |article| %>
        <div class="col-md-12 box">
          <div class="col-md-3 wel-grid1">
            <div class="image-box agileits_service_grid_btm_left1">
              <% if article.image.file? %>
                  <%= image_tag article.image.url(), :width=> 230, :height => 230 %>
              <% else %>
                  <%= image_tag("jobs/job-default.png", :width=> 230, :height => 230) %>
              <% end %>
            </div>
          </div>
          <div class="col-md-9 wel-grid">
            <h4><%= article.title %>
              <h6><% if can? :edit, article %>
                  <%= link_to icon("pencil-square-o",'Editar'), edit_article_path(article) %>
              <% end %>
              <% if can? :delete, article %>
                  <%= link_to icon('trash-o','Eliminar'), article, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %></h6>
            </h4>
            <hr>
            <label class="panel">Created at <%= icon("calendar")%> <%= article.created_at %></label>
            <p><%= article.text[0...250] %></p>
            <%= link_to "Ver Articulo Completo", article,:class=>"btn btn-common" %>
          </div>
        </div>

    <% end %>


</div>
<%  @total = (page_entries_info articles).split('<b>')
    if @total.size == 3
      @total = @total[2].split('</b>')
    end
%>
<% if @total[0].to_i >= 10 %>
    <%= paginate articles %>
<% end  %>


app/views/articles/_show.html.erb
<div id="product-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= title %></h4>
      </div>
      <!-- modal body -->
      <div class="modal-body">

        <div class="box container-fluid">
          <div class="col-md-4">
            <div class="agileits_service_grid_btm_left1">
              <% if @job.image.file? %>
                  <%= image_tag @job.image.url(), :width=> 150, :height => 150 %>
              <% else %>
                  <%= image_tag("jobs/job-default.png", :width=> 150, :height => 150) %>
              <% end %>
            </div>
          </div>
          <div class="col-md-8">
            <div class="text-left">
              <h3> <strong><%= @job.title %></strong></h3>
                <%= link_to icon("list-alt",'Trabajos'), jobs_path ,:class=>"btn btn-default btn-xs" %>
                <% if can? :edit, @job %>
                    <%= link_to icon("pencil-square-o",'Editar'), edit_job_path(@job),:class=>"btn btn-default btn-xs" %>
                <% end %>
                <% if can? :delete, @job %>
                    <%= link_to icon('trash-o','Eliminar'), @job, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-default btn-xs" %>
                <% end %>
              <p>Publicado por:<%= @job.company.company %></p>
              <div class="meta">
                <span><%= icon ("briefcase") %> <%= @job.category.category %></span><br>
                <span> <%= icon ("map-marker") %> <%= @job.m_country.ncountry %></span><br>
                <span> <%= icon ("calendar") %> <%= @job.created_at %></span><br>
              </div>
              <strong class="price"><%= icon ("money") %> <%= @job.money %> $</strong>
              <a href="#" class="btn btn-border btn-sm">Freelance</a>
              <a href="#" class="btn btn-common btn-sm">Aplicar</a>
            </div>
          </div>
          <hr>
          <div class="clearfix col-lg-12">
            <div class="col-lg-12"></div>
            <h4>Overview</h4>
            <p> <%= @job.description %> </p><br>
            <h4>Requirements</h4>
            <p> <%= @job.requisitos %> </p><br>
            <h4>Benefits</h4>
            <p> <%= @job.beneficios %> </p>
            <a href="#" class="btn btn-common">Apply for this Job Now</a>
          </div>
        </div>

      </div>
      <!-- end modal body -->
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<br>
<div class="">
  <div class="container">
    <div class="panel panel-default">
      <div class="panel-heading">
        Listado de Noticias
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-6">
            <%= form_for_filterrific @filterrific do |f| %>
                Records to show
                <%= select_tag :cantd, options_for_select([10,20,40].to_a, nil)  %>
                Search
                <%= f.text_field(   :search_query, class: 'filterrific-periodically-observed' ) %>
                <%# add an automated spinner to your form when the list is refreshed %>
                <%= render_filterrific_spinner %>
            <% end %>
            <%#= link_to( 'Reset filters', reset_filterrific_url, class: "btn-normal btn-sm") %>
          </div>
          <div class="col-lg-6">
            <div class="right">
              <%#= link_to icon('file-code-o','CSV'), articles_path(format: "csv") %>
              <%#= link_to icon('file-excel-o','Excel'), articles_path(format: "xls") %>
              <%= link_to icon('plus-circle','Noticia'), new_article_path %>
            </div>
          </div>
        </div>
        <hr>
        <%= render(        partial: 'articles/list',        locals: { articles: @articles }    ) %>
      </div>
      <div class="panel-footer">
        &nbsp;<i class="right">articles</i>
      </div>
    </div>
  </div>
</div>




app/views/articles/index.js.erb
<% js = escape_javascript(
  render(partial: 'articles/list', locals: { articles: @articles })
) %>
$("#filterrific_results").html("<%= js %>");


app/views/articles/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">TITLE</Data></Cell>
        <Cell><Data ss:Type="String">TEXT</Data></Cell>
      </Row>
      <% @articles.each do |article| %>
          <Row>
            <Cell><Data ss:Type="Number"><%= article.id %></Data></Cell>
            <Cell><Data ss:Type="String"><%= article.title %></Data></Cell>
            <Cell><Data ss:Type="String"><%= article.text %></Data></Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>


app/views/articles/new.html.erb

<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>




app/views/articles/show.html.erb
<div class="container">
  <div class="col-md-12 box">

    <div class="col-md-4 wel-grid1">
      <div class="image-box agileits_service_grid_btm_left1">
        <% if @article.image.file? %>
            <%= image_tag @article.image.url(), :width=> 350, :height => 350 %>
        <% else %>
            <%= image_tag("jobs/job-default.png", :width=> 350, :height => 350) %>
        <% end %>
      </div>
    </div>

    <div class="col-md-8 wel-grid">
      <h4><%= @article.title %></h4>
      <%= link_to icon("list-alt",'Noticias'), articles_path ,:class=>"btn btn-default btn-xs" %>
      <% if can? :edit, @article %>
          <%= link_to icon("pencil-square-o",'Edit'), edit_article_path(@article),:class=>"btn btn-default btn-xs" %>
      <% end %>
      <% if can? :delete, @article %>
          <%= link_to icon('trash-o','Eliminar'), @article, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-default btn-xs" %>
      <% end %>
      <hr>
      <label class="panel">Created at <%= icon("calendar")%> <%= @article.created_at %></label>
      <%#= link_to icon("mail-reply","Back"), articles_path %>
      <p><%= @article.text %></p>
    </div>

  </div>
</div>


app/views/articles/show.js.erb
$('<%= j render "show", title: "Aplicar Form" %>').modal();