config/routes.rb
Rails.application.routes.draw do

  devise_for :employees
  #devise_for :candidates
  devise_for :companies
  devise_for :users

  resources :employees
  resources :m_countries
  resources :messageemployees
  resources :countries
  resources :aplicationjobs
  resources :categories
  resources :companies
  resources :jobs
  resources :articles

  get 'aplicationjobs/new/:job_id', to: 'aplicationjobs#new'
  get 'messageemployees/new/:candidate_id', to: 'messageemployees#new'

  #devise_for :users
  #match '/auth/:provider/callback', :to => 'sessions#create', via: :get
  get 'home', to: 'home#index'
       root :to => "home#index" #page index by default

  #resources :administration
  get 'administration/jobs', to: 'administration#jobs'  #donde se guardan los trabajos aplicados para un usuario
  get 'administration/companies', to: 'administration#companies'  #donde se guardan las aplicaciones de trabajo para esa compannia
  get 'administration/employees', to: 'administration#employees' #donde se guardan los mensajes de los usuarios empleados

  post 'search', to: 'home#search'

end

app/models/aplicationjob.rb
class Aplicationjob < ApplicationRecord
  belongs_to :job
  belongs_to :employee

  #para descargar formato csv
  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |aplicationjob|
        csv << aplicationjob.attributes.values_at(*column_names)
      end
    end
  end

  #self.page = 5
  #gema filterrific para paginado y filtrado
  filterrific(
      default_filter_params: { sorted_by: 'created_at_desc' },
      available_filters: [
          :sorted_by,
          :search_query,
          :with_country_id,
          :with_created_at_gte
      ]
  )

  scope :search_query, lambda { |query|
    return nil  if query.blank?
    # condition query, parse into individual keywords
    terms = query.downcase.split(/\s+/)
    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conditions = 3
    where(
        terms.map {
          or_clauses = [
              "LOWER(jobs.title) LIKE ?",
              "LOWER(jobs.country) LIKE ?",
              "LOWER(jobs.job_stat) LIKE ?"
          ].join(' OR ')
          "(#{ or_clauses })"
        }.join(' AND '),
        *terms.map { |e| [e] * num_or_conditions }.flatten
    )
  }

  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
      when /^created_at_/
        order("jobs.created_at #{ direction }")
      when /^name_/
        order("LOWER(jobs.title) #{ direction }, LOWER(jobs.title) #{ direction }")
      else
        raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }
  scope :with_category_id, lambda { |category_ids|
    where(:category_id => [*category_ids])
  }
  scope :with_company_id, lambda { |company_ids|
    where(:company_id => [*company_ids])
  }
  scope :with_created_at_gte, lambda { |ref_date|
    where('jobs.created_at >= ?', ref_date)
  }

  delegate :name, :to => :country, :prefix => true

  def self.options_for_sorted_by
    [
        ['Name (a-z)', 'name_asc'],
        ['Registration date (newest first)', 'created_at_desc'],
        ['Registration date (oldest first)', 'created_at_asc'],
        ['Country (a-z)', 'country_name_asc']
    ]
  end

  def full_name
    [last_name, first_name].compact.join(', ')
  end

  def decorated_created_at
    created_at.to_date.to_s(:long)
  end


end

app/controllers/aplicationjobs_controller.rb
class AplicationjobsController < ApplicationController
  before_action :set_aplicationjob, only: [:show, :edit, :update, :destroy]

  # GET /aplicationjobs
  # GET /aplicationjobs.json
  def index
    #@aplicationjobs = Aplicationjob.all
    @filterrific = initialize_filterrific(
        Aplicationjob,
        params[:filterrific]
    ) or return
    @aplicationjobs = @filterrific.find.page(params[:page]).per(params[:cantd])
  end

  # GET /aplicationjobs/1
  # GET /aplicationjobs/1.json
  def show
  end

  # GET /aplicationjobs/new
  def new
    @aplicationjob = Aplicationjob.new
    @job = Job.find(params[:job_id])
  end

  # GET /aplicationjobs/1/edit
  def edit
  end

  # POST /aplicationjobs
  # POST /aplicationjobs.json
  def create
    @aplicationjob = Aplicationjob.new(aplicationjob_params)

    respond_to do |format|
      if @aplicationjob.save
        format.html { redirect_to administration_jobs_url, notice: 'Aplicationjob was successfully created.' }
        format.json { render :show, status: :created, location: administration_jobs_url }
      else
        format.html { render :new }
        format.json { render json: @aplicationjob.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aplicationjobs/1
  # PATCH/PUT /aplicationjobs/1.json
  def update
    respond_to do |format|
      if @aplicationjob.update(aplicationjob_params)
        format.html { redirect_to administration_jobs_url, notice: 'Aplicationjob was successfully updated.' }
        format.json { render :show, status: :ok, location: administration_jobs_url }
      else
        format.html { render :edit }
        format.json { render json: @aplicationjob.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aplicationjobs/1
  # DELETE /aplicationjobs/1.json
  def destroy
    @aplicationjob.destroy
    respond_to do |format|
      format.html { redirect_to aplicationjobs_url, notice: 'Aplicationjob was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aplicationjob
      @aplicationjob = Aplicationjob.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aplicationjob_params
      params.require(:aplicationjob).permit(:job_id, :employee_id, :description)
    end
end

app/helpers/aplicationjobs_helper.rb
module AplicationjobsHelper
end

app/views/aplicationjobs/_form.html.erb
<%= form_for(aplicationjob) do |f| %>
  <% if aplicationjob.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aplicationjob.errors.count, "error") %> prohibited this aplicationjob from being saved:</h2>

      <ul>
      <% aplicationjob.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= @job.title %>
    <%= f.hidden_field :job_id,value: @job.id %>
  </div>

  <div class="field">
    <%= current_user.employee.fullname %>
    <%= f.hidden_field :employee_id,value: current_user.employee_id %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aplicationjobs/_list.html.erb
<div id="filterrific_results">
  <div>
    <%= page_entries_info aplicationjobs %>
  </div>

  <table class="table table-bordered table-header table-stripered">
    <thead>
    <tr>
      <th>Job</th>
      <th>Employee</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
    <% aplicationjobs.each do |aplicationjob| %>
        <tr>
          <td><%= aplicationjob.job %></td>
          <td><%= aplicationjob.employee %></td>
          <td><%= aplicationjob.description %></td>
          <td><%= link_to icon('eye'), aplicationjob %></td>
          <td><%= link_to icon('pencil-square-o'), edit_aplicationjob_path(aplicationjob) %></td>
          <td><%= link_to icon('trash-o'), aplicationjob, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>
<%  @total = (page_entries_info aplicationjobs).split('<b>')
    if @total.size == 3
      @total = @total[2].split('</b>')
    end
%>
<% if @total[0].to_i >= 10 %>
<%= paginate aplicationjobs %>
<% end  %>

app/views/aplicationjobs/_show.html.erb
<div id="product-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= title %></h4>
      </div>
      <!-- modal body -->
      <div class="modal-body">

        <div class="box container-fluid">
          <div class="col-md-4">
            <div class="agileits_service_grid_btm_left1">
              <% if @job.image.file? %>
                  <%= image_tag @job.image.url(), :width=> 150, :height => 150 %>
              <% else %>
                  <%= image_tag("jobs/job-default.png", :width=> 150, :height => 150) %>
              <% end %>
            </div>
          </div>
          <div class="col-md-8">
            <div class="text-left">
              <h3> <strong><%= @job.title %></strong></h3>
                <%= link_to icon("list-alt",'Trabajos'), jobs_path ,:class=>"btn btn-default btn-xs" %>
                <% if can? :edit, @job %>
                    <%= link_to icon("pencil-square-o",'Editar'), edit_job_path(@job),:class=>"btn btn-default btn-xs" %>
                <% end %>
                <% if can? :delete, @job %>
                    <%= link_to icon('trash-o','Eliminar'), @job, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-default btn-xs" %>
                <% end %>
              <p>Publicado por:<%= @job.company.company %></p>
              <div class="meta">
                <span><%= icon ("briefcase") %> <%= @job.category.category %></span><br>
                <span> <%= icon ("map-marker") %> <%= @job.m_country.ncountry %></span><br>
                <span> <%= icon ("calendar") %> <%= @job.created_at %></span><br>
              </div>
              <strong class="price"><%= icon ("money") %> <%= @job.money %> $</strong>
              <a href="#" class="btn btn-border btn-sm">Freelance</a>
              <a href="#" class="btn btn-common btn-sm">Aplicar</a>
            </div>
          </div>
          <hr>
          <div class="clearfix col-lg-12">
            <div class="col-lg-12"></div>
            <h4>Overview</h4>
            <p> <%= @job.description %> </p><br>
            <h4>Requirements</h4>
            <p> <%= @job.requisitos %> </p><br>
            <h4>Benefits</h4>
            <p> <%= @job.beneficios %> </p>
            <a href="#" class="btn btn-common">Apply for this Job Now</a>
          </div>
        </div>

      </div>
      <!-- end modal body -->
    </div>
  </div>
</div>

app/views/aplicationjobs/edit.html.erb
<h1>Editing Aplicationjob</h1>

<%= render 'form', aplicationjob: @aplicationjob %>

<%= link_to 'Show', @aplicationjob %> |
<%= link_to 'Back', aplicationjobs_path %>

app/views/aplicationjobs/index.html.erb
<br>
<div class="panel">
  <div class="panel panel-default">
    <div class="panel-heading">
      Admin Aplication-Jobs
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-lg-6">
          <%= form_for_filterrific @filterrific do |f| %>
              Records to show
              <%= select_tag :cantd, options_for_select([5,10,20,40].to_a, nil)  %>
              Search
              <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
              <%= f.text_field(   :search_query, class: 'filterrific-periodically-observed' ) %>
              <%# add an automated spinner to your form when the list is refreshed %>
              <%= render_filterrific_spinner %>
          <% end %>
          <%#= link_to( 'Reset filters', reset_filterrific_url, class: "btn-normal btn-sm") %>
        </div>
        <div class="col-lg-6">
          <div class="right">
            Download:
            <%= link_to icon('file-code-o','CSV'), aplicationjob_path(format: "csv") %> |
            <%= link_to icon('file-excel-o','Excel'), aplicationjob_path(format: "xls") %>
            <%= link_to icon('plus-circle','Add Aplication-Job'), new_aplicationjob_path , class: "btn-primary btn-sm" %>
          </div>
        </div>
      </div>
      <hr>
      <%= render(        partial: 'aplicationjobs/list',        locals: { aplicationjobs: @aplicationjobs }    ) %>
    </div>
    <div class="panel-footer">
      &nbsp;<i class="right">aplication jobs</i>
    </div>
  </div>
</div>

app/views/aplicationjobs/index.js.erb
<% js = escape_javascript(
  render(partial: 'aplicationjobs/list', locals: { aplicationjobs: @aplicationjobs })
) %>
$("#filterrific_results").html("<%= js %>");


app/views/aplicationjobs/new.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      Formulario de Aplicacion para el siguiente Trabajo
    </div>
    <div class="panel-body">
      <div class="container-fluid">
        <%= render 'form', aplicationjob: @aplicationjob , job: @job %>
      </div>
    </div>
  </div>
</div>
<%#= link_to 'Back', aplicationjobs_path %>

app/views/aplicationjobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Job:</strong>
  <%= @aplicationjob.job %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @aplicationjob.employee %>
</p>

<p>
  <strong>Description:</strong>
  <%= @aplicationjob.description %>
</p>

<%= link_to 'Edit', edit_aplicationjob_path(@aplicationjob) %> |
<%= link_to 'Back', aplicationjobs_path %>

app/views/aplicationjobs/show.js.erb
$('<%= j render "show", title: "Aplicar Form" %>').modal();