config/routes.rb
Rails.application.routes.draw do

  devise_for :employees
  #devise_for :candidates
  devise_for :companies
  devise_for :users

  resources :employees
  resources :m_countries
  resources :messageemployees
  resources :countries
  resources :aplicationjobs
  resources :categories
  resources :companies
  resources :jobs
  resources :articles

  get 'aplicationjobs/new/:job_id', to: 'aplicationjobs#new'
  get 'messageemployees/new/:candidate_id', to: 'messageemployees#new'

  #devise_for :users
  #match '/auth/:provider/callback', :to => 'sessions#create', via: :get
  get 'home', to: 'home#index'
       root :to => "home#index" #page index by default

  #resources :administration
  get 'administration/jobs', to: 'administration#jobs'  #donde se guardan los trabajos aplicados para un usuario
  get 'administration/companies', to: 'administration#companies'  #donde se guardan las aplicaciones de trabajo para esa compannia
  get 'administration/employees', to: 'administration#employees' #donde se guardan los mensajes de los usuarios empleados

  post 'search', to: 'home#search'

end

app/models/messageemployee.rb
class Messageemployee < ApplicationRecord
  belongs_to :employee
  belongs_to :company

  #para descargar formato csv
  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |aplicationjob|
        csv << aplicationjob.attributes.values_at(*column_names)
      end
    end
  end

  #self.page = 5
  #gema filterrific para paginado y filtrado
  filterrific(
      default_filter_params: { sorted_by: 'created_at_desc' },
      available_filters: [
          :sorted_by,
          :search_query,
          :with_country_id,
          :with_created_at_gte
      ]
  )

  scope :search_query, lambda { |query|
    return nil  if query.blank?
    # condition query, parse into individual keywords
    terms = query.downcase.split(/\s+/)
    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conditions = 3
    where(
        terms.map {
          or_clauses = [
              "LOWER(jobs.title) LIKE ?",
              "LOWER(jobs.country) LIKE ?",
              "LOWER(jobs.job_stat) LIKE ?"
          ].join(' OR ')
          "(#{ or_clauses })"
        }.join(' AND '),
        *terms.map { |e| [e] * num_or_conditions }.flatten
    )
  }

  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
      when /^created_at_/
        order("jobs.created_at #{ direction }")
      when /^name_/
        order("LOWER(jobs.title) #{ direction }, LOWER(jobs.title) #{ direction }")
      else
        raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }
  scope :with_category_id, lambda { |category_ids|
    where(:category_id => [*category_ids])
  }
  scope :with_company_id, lambda { |company_ids|
    where(:company_id => [*company_ids])
  }
  scope :with_created_at_gte, lambda { |ref_date|
    where('jobs.created_at >= ?', ref_date)
  }

  delegate :name, :to => :country, :prefix => true

  def self.options_for_sorted_by
    [
        ['Name (a-z)', 'name_asc'],
        ['Registration date (newest first)', 'created_at_desc'],
        ['Registration date (oldest first)', 'created_at_asc'],
        ['Country (a-z)', 'country_name_asc']
    ]
  end

  def full_name
    [last_name, first_name].compact.join(', ')
  end

  def decorated_created_at
    created_at.to_date.to_s(:long)
  end

end

app/controllers/messageemployees_controller.rb
class MessageemployeesController < ApplicationController
  before_action :set_messageemployee, only: [:show, :edit, :update, :destroy]

  # GET /messageemployees
  # GET /messageemployees.json
  def index
    @messageemployees = Messageemployee.all
  end

  # GET /messageemployees/1
  # GET /messageemployees/1.json
  def show
  end

  # GET /messageemployees/new
  def new
    @messageemployee = Messageemployee.new
    @employee = Employee.find(params[:candidate_id])
  end

  # GET /messageemployees/1/edit
  def edit
  end

  # POST /messageemployees
  # POST /messageemployees.json
  def create
    @messageemployee = Messageemployee.new(messageemployee_params)

    respond_to do |format|
      if @messageemployee.save
        format.html { redirect_to @messageemployee, notice: 'Messageemployee was successfully created.' }
        format.json { render :show, status: :created, location: @messageemployee }
      else
        format.html { render :new }
        format.json { render json: @messageemployee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messageemployees/1
  # PATCH/PUT /messageemployees/1.json
  def update
    respond_to do |format|
      if @messageemployee.update(messageemployee_params)
        format.html { redirect_to @messageemployee, notice: 'Messageemployee was successfully updated.' }
        format.json { render :show, status: :ok, location: @messageemployee }
      else
        format.html { render :edit }
        format.json { render json: @messageemployee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messageemployees/1
  # DELETE /messageemployees/1.json
  def destroy
    @messageemployee.destroy
    respond_to do |format|
      format.html { redirect_to messageemployees_url, notice: 'Messageemployee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_messageemployee
      @messageemployee = Messageemployee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def messageemployee_params
      params.require(:messageemployee).permit(:employee_id, :company_id, :mail)
    end
end

app/helpers/messageemployees_helper.rb
module MessageemployeesHelper
end

app/views/messageemployees/_form.html.erb
<%= form_for(messageemployee) do |f| %>
  <% if messageemployee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(messageemployee.errors.count, "error") %> prohibited this messageemployee from being saved:</h2>

      <ul>
      <% messageemployee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :employee_id %>
    <%= f.text_field :employee_id %>
  </div>

  <div class="field">
    <%= f.label :company_id %>
    <%= f.text_field :company_id %>
  </div>

  <div class="field">
    <%= f.label :mail %>
    <%= f.text_area :mail %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messageemployees/_list.html.erb
<div id="filterrific_results">
  <div>
    <%= page_entries_info jobs %>
  </div>

  <table class="table table-bordered table-header table-stripered">
    <tr>
      <th>title</th>
      <th>country</th>
      <th>company</th>
      <th>publicate_at</th>
      <th>active</th>
      <th>description</th>
      <th>picture</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
    <% jobs.each do |job| %>
        <tr>
          <td><%= job.title %></td>
          <td><%= job.country %></td>
          <td><%= job.company_id %></td>
          <td><%= job.publicate_at %></td>
          <td><%= job.active %></td>
          <td><%= job.description %></td>
          <td><%= job.picture %></td>
          <td><%= job.job_stat %></td>
          <td><%= link_to 'Show', job %>  <%= link_to 'Edit', edit_job_path(job) %>
            <%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
    <% end %>
  </table>
</div>
<%  @total = (page_entries_info jobs).split('<b>')
    if @total.size == 3
      @total = @total[2].split('</b>')
    end
%>
<% if @total[0].to_i >= 10 %>
<%= paginate jobs %>
<% end  %>

app/views/messageemployees/_new.html.erb
<div id="product-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"> Responder mensaje </h4>
      </div>
      <!-- modal body -->
      <div class="modal-body">
        <div class="container-fluid">
          <%= form_for(@messageemployee) do |f| %>
              <% if @messageemployee.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@messageemployee.errors.count, "error") %> prohibited this messageemployee from being saved:</h2>
                    <ul>
                      <% @messageemployee.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                      <% end %>
                    </ul>
                  </div>
              <% end %>
              <div class="col-md-6 hidden">
                <%= f.label "Candidato" %>
                <%= f.text_field :employee_id , value: @employee.id , class: "form-control" %>
              </div>
              <div class="col-md-6 hidden">
                <%= f.label :company_id %>
                <%= f.text_field :company_id , value: current_user.company_id %>
              </div>
              <div class="col-md-12">
                <%= f.label :mail %>
                <%= f.text_area :mail , class: "form-control" %>
              </div>
              <div class="col-md-12 separate-5">
                <%= f.submit class: "btn btn-primary",value: "Create" %>
              </div>
          <% end %>
        </div>
      </div>
      <!-- end modal body -->
    </div>
  </div>
</div>

app/views/messageemployees/edit.html.erb
<h1>Editing Messageemployee</h1>

<%= render 'form', messageemployee: @messageemployee %>

<%= link_to 'Show', @messageemployee %> |
<%= link_to 'Back', messageemployees_path %>

app/views/messageemployees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messageemployees</h1>

<table>
  <thead>
    <tr>
      <th>Employee</th>
      <th>Company</th>
      <th>Mail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messageemployees.each do |messageemployee| %>
      <tr>
        <td><%= messageemployee.employee %></td>
        <td><%= messageemployee.company %></td>
        <td><%= messageemployee.mail %></td>
        <td><%= link_to icon('eye'), messageemployee %></td>
        <td><%= link_to icon('pencil-square-o'), edit_messageemployee_path(messageemployee) %></td>
        <td><%= link_to icon('trash-o'), messageemployee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Messageemployee', new_messageemployee_path %>

app/views/messageemployees/index.js.erb
<% js = escape_javascript(
  render(partial: 'messageemployees/list', locals: { messageemployees: @messageemployees })
) %>
$("#filterrific_results").html("<%= js %>");


app/views/messageemployees/new.html.erb
<h1>New Messageemployee</h1>

<%= render 'form', messageemployee: @messageemployee %>

<%= link_to 'Back', messageemployees_path %>

app/views/messageemployees/new.js.erb
$('<%= j render "new", title: "Responder Mensaje" %>').modal();

app/views/messageemployees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee:</strong>
  <%= @messageemployee.employee %>
</p>

<p>
  <strong>Company:</strong>
  <%= @messageemployee.company %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @messageemployee.mail %>
</p>

<%= link_to 'Edit', edit_messageemployee_path(@messageemployee) %> |
<%= link_to 'Back', messageemployees_path %>